name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --html=report.html

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: report.html

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t kirinvbg/sg:latest --push .
        docker push kirinvbg/sg:latest

# echo "" | docker login -u kirinvbg --password-stdin
# docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.REGISTRY_USERNAME}}/sg:latest .
# docker push ${{secrets.REGISTRY_USERNAME}}/sg:latest